### ISSUE TITLE
Jak dołączyć do Teamu

### ISSUE THREAD

**Issue by Kitsunje** [kbartek05/Spolszczenie-Deltarune#2]
Umm mam problemy z kontaktem z Tobą ^^'
Napisałam komentarz na YT
Dołączyłam do Discorda
No i pisze tutaj ale nie za bardzo sie znam na tej stronce

Can you give me a helping hand? 
Please ;^;

**Comment by kbartek05** [comment]
Sprawa wyjaśniona na Discordzie, zamykam
